/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.SalaryComputation;

import com.mycompany.SalaryComputation.SalaryComp;
import javax.swing.JOptionPane;

/**
 *
 * @author Michaella Eroles
 */
public class TestMethodOverloading extends javax.swing.JFrame {

    /**
     * Creates new form TestMethodOverloading
     */
    public TestMethodOverloading() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHoursWorked = new javax.swing.JTextField();
        txtRatePerHour = new javax.swing.JTextField();
        txtTax = new javax.swing.JTextField();
        btnCompute = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Hours Worked");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 112, 84, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Rate Per Hour");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 155, 84, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Tax");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 192, 26, -1));

        txtHoursWorked.setBackground(new java.awt.Color(255, 204, 204));
        txtHoursWorked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoursWorkedActionPerformed(evt);
            }
        });
        getContentPane().add(txtHoursWorked, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 109, 188, -1));

        txtRatePerHour.setBackground(new java.awt.Color(255, 204, 204));
        txtRatePerHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRatePerHourActionPerformed(evt);
            }
        });
        getContentPane().add(txtRatePerHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 152, 188, -1));

        txtTax.setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().add(txtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 192, 188, -1));

        btnCompute.setBackground(new java.awt.Color(255, 153, 153));
        btnCompute.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCompute.setText("COMPUTE");
        btnCompute.setBorder(null);
        btnCompute.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCompute.setMargin(new java.awt.Insets(2, 16, 3, 16));
        btnCompute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputeActionPerformed(evt);
            }
        });
        getContentPane().add(btnCompute, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 242, 80, 26));

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel1.setText("SALARY COMPUTATION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(227, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(204, 204, 204))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 635, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHoursWorkedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoursWorkedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoursWorkedActionPerformed

    private void btnComputeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputeActionPerformed
        // TODO add your handling code here:
        SalaryComp s = new SalaryComp();
        
        String  hoursWorked = txtHoursWorked.getText();
        String ratePerHour = txtRatePerHour.getText();
        String tax = txtTax.getText();
        
        if (hoursWorked.contains(".") || ratePerHour.contains(".") || tax.contains(".")){
            double h = Double.parseDouble(hoursWorked);
            double r = Double.parseDouble(ratePerHour);
            double t = Double.parseDouble(tax);
            JOptionPane.showMessageDialog(null, s.netSalary(h,r,t));
        } else {
            int h = Integer.parseInt(hoursWorked);
            int r = Integer.parseInt(ratePerHour);
            int t = Integer.parseInt(tax);
            JOptionPane.showMessageDialog(null, s.netSalary(h,r,t));
        }
    }//GEN-LAST:event_btnComputeActionPerformed

    private void txtRatePerHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRatePerHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRatePerHourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestMethodOverloading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestMethodOverloading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestMethodOverloading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestMethodOverloading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestMethodOverloading().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompute;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtHoursWorked;
    private javax.swing.JTextField txtRatePerHour;
    private javax.swing.JTextField txtTax;
    // End of variables declaration//GEN-END:variables
}
